### PR TITLE
Added converting html encoding to UTF-8

### PR DESCRIPTION
**Pull request by akmubi**

### CODE REVIEW

**Comment by anaskhan96** [comment]
Hi @akmubi, any idea why this was closed? Apologies for not having gotten back sooner, been real busy with work :/

If this corresponds to #22, i'll be happy to have a look

**Comment by akmubi** [comment]
@anaskhan96 it was closed because i made a mistake. I wrote "**golnag**.org/x/net/html/charset" instead of "**golang**.org/x/net/html/charset" :{

**Comment by anaskhan96** [comment]
No worries, I've reopened the PR and converted this to a draft - this means that it's still a WIP
If it's already completed or once you complete it, we can turn this back into an open PR for review and then proceed further :)

**Comment by akmubi** [comment]
OK. Turned out that i've already fixed this mistake :0

**Comment by anaskhan96** [comment]
Thank you for the PR! :)

**Pull request merged**
